# Generated by Django 6.0.4 on 2026-04-20 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_room_current_track_id_room_is_playing_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='album_art',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='track',
            name='spotify_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='track',
            name='duration',
            field=models.IntegerField(help_text='Duration in milliseconds'),
        ),
        migrations.AlterField(
            model_name='track',
            name='source_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
